### ISSUE TITLE
AJAX error

### ISSUE THREAD

**Issue by oabdalla** [lygav/phpbbPostLike#2]
I installed and enabled the extension with no issues however if I click on the "Like" button that shows up under post author photo I get the following error: AJAX error. Not Found
My Board version:  3.1.6

**Comment by lygav** [comment]
Hi @oabdalla can you try and give me more details. For example the full error message, browser etc.
Thank you

**Comment by oabdalla** [comment]
Hello Vlad
Thank you for getting back to me.
Attached are screen shots showing the enabled extension and the error
message I or any other forum user gets when clicking on the like button.
There are not much details to the error message except that pop-up message
that says "AJAX ERROR. Not Found". I tried this in Chrome, Firefox, MS Edge
and got the same exact error message. This happened on phpBB 3.1.6 and
continued to happen after we upgraded to 3.1.9 (the latest release). I have
no issues with other extensions.
I also think it will make sense if the "Like" button appears in the post
title (where the quote button is for example) instead of showing under the
poster's profile info.
Thanks,
Omer

**Comment by lygav** [comment]
Hi, ok i think i know what the problem.
I'll try to fix and push an update in a couple of days

**Comment by oabdalla** [comment]
Thank you so much and good luck

**Comment by lygav** [comment]
@oabdalla Hi, do you have a url_rewriting enabled on your apache?
If no, please try enabling it.
Anyway - please see if you can give me a link to your forum.
I think we can resolve it.
