### ISSUE TITLE
change output location?

### ISSUE THREAD

**Issue by raafirivero** [lygav/phpbbPostLike#3]
Is there any way to make this output somewhere other than under the user's profile? For my site the ideal place for the like button would be in the bottom right of a post (like how they appear in [this forum](http://www.eoshd.com/comments/topic/21546-rx100v-continuous-af-in-slowmo/)). Any ideas how to set that up?

**Comment by lygav** [comment]
Hello @raafirivero , i think one need to be signed-in to see the 'like' button on the forum you provided so i couldn't really see what exactly do you mean, though i think i understand.

Regarding the question - i've experimented with different positions, and i've found that it messes up the appearance of the forum on different screen sizes/layouts.

**Comment by raafirivero** [comment]
You're probably right. I'm working on (re-)building a [forum](kinecommunity.com) that was dormant and have installed this plugin. Right now, with the like button under the person's name it feels as if you're liking that person instead of what they posted. the other forum I linked to earlier. I don't think it should be done in CSS as that would never work for every forum, but I wish there was a way that the like button went under a post so it was clear that's what you're liking.
