### ISSUE TITLE
Enable Extension SQL Error

### ISSUE THREAD

**Issue by AutoJunkie79** [lygav/phpbbPostLike#4]
Running phpBB 3.2.0 with PHP 7.1 against MSSQL on Windows 2016. I'm getting the following error when attempting to enable the extension.

Thanks for your help!

![capture](https://cloud.githubusercontent.com/assets/25411186/22833014/4c2f847c-ef7e-11e6-895d-1f015843e322.PNG)

**Comment by lygav** [comment]
Hi @AutoJunkie79 , looks like your sqlserver doesn't like backticks.
I cannot test it right now, but you can use the following migrations file i've edited the backticks away. Just substitute the: migrations/r1.php with this one.

```php
<?php

namespace lygav\phpbbPostLike\migrations;

class r1 extends \phpbb\db\migration\migration
{
	public function update_data ()
	{
		return [
			['custom', [[$this, 'add_timestamp_to_table']]]
		];
	}

	public function update_schema ()
	{
		return [
			'add_tables' => [
				$this->table_prefix . 'post_likes' => [
					'COLUMNS'     => [
						'post_id'   => ['UINT:8', 0],
						'user_id'   => ['UINT:8', 0],
					],
					'PRIMARY_KEY' => [
						'user_id',
						'post_id'
					],
					'KEYS' => [
							'u_i_d' => ['INDEX', 'user_id']
						]
				]
			]
		];
	}

	public function add_timestamp_to_table ()
	{
		$this->db->sql_query("ALTER TABLE  ".$this->table_prefix."post_likes ADD  occured_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER  user_id");
	}

	public function revert_schema ()
	{
		return [
			'drop_tables' => [
				$this->table_prefix.'post_likes'
			]
		];
	}


}

**Comment by AutoJunkie79** [comment]
Sorry no beans - the error message is just slightly different this time. I wish I could help out more, but I'm a total noob when it comes to PHP and MSSQL queries...

![capture2](https://cloud.githubusercontent.com/assets/25411186/22889403/06c9c392-f1d7-11e6-9c7a-60ccd8a193d6.PNG)

**Comment by lygav** [comment]
@AutoJunkie79 Hi i think this is a MySQL-MSSQL SQL syntax in-compatibility issue.
Is this is a new forum? Can you possibly switch to mysql? 
If not, i probably need to check alternative compatible syntax for MSSQL..I just don't know
MSSQL very well

**Comment by AutoJunkie79** [comment]
@lygav Yeah that definitely seems to be the case. More specifically, it seems to be an issue with how to pass the PHP variables into a MSSQL query. I can't use MySQL as my organization doesn't support it at this time.

I guess I'll try to play with it when I have some spare time. Just quickly googling it seems like this is a pretty common struggle for those working with PHP and MSSQL. Hopefully there's an answer out there. :)

If you have time and are interested, Microsoft does offer MSSQL for free: https://www.microsoft.com/en-us/sql-server/sql-server-editions-express

Thanks for your help
